/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	v1alpha1 "k8s.io/autoscaler/hvpa-controller/pkg/apis/autoscaling/v1alpha1"
	scheme "k8s.io/autoscaler/hvpa-controller/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

// HvpasGetter has a method to return a HvpaInterface.
// A group's client should implement this interface.
type HvpasGetter interface {
	Hvpas(namespace string) HvpaInterface
}

// HvpaInterface has methods to work with Hvpa resources.
type HvpaInterface interface {
	Create(*v1alpha1.Hvpa) (*v1alpha1.Hvpa, error)
	Update(*v1alpha1.Hvpa) (*v1alpha1.Hvpa, error)
	UpdateStatus(*v1alpha1.Hvpa) (*v1alpha1.Hvpa, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Hvpa, error)
	List(opts v1.ListOptions) (*v1alpha1.HvpaList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Hvpa, err error)
	HvpaExpansion
}

// hvpas implements HvpaInterface
type hvpas struct {
	client rest.Interface
	ns     string
}

// newHvpas returns a Hvpas
func newHvpas(c *AutoscalingV1alpha1Client, namespace string) *hvpas {
	return &hvpas{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hvpa, and returns the corresponding hvpa object, and an error if there is any.
func (c *hvpas) Get(name string, options v1.GetOptions) (result *v1alpha1.Hvpa, err error) {
	result = &v1alpha1.Hvpa{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hvpas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Hvpas that match those selectors.
func (c *hvpas) List(opts v1.ListOptions) (result *v1alpha1.HvpaList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HvpaList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hvpas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hvpas.
func (c *hvpas) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hvpas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a hvpa and creates it.  Returns the server's representation of the hvpa, and an error, if there is any.
func (c *hvpas) Create(hvpa *v1alpha1.Hvpa) (result *v1alpha1.Hvpa, err error) {
	result = &v1alpha1.Hvpa{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hvpas").
		Body(hvpa).
		Do().
		Into(result)
	return
}

// Update takes the representation of a hvpa and updates it. Returns the server's representation of the hvpa, and an error, if there is any.
func (c *hvpas) Update(hvpa *v1alpha1.Hvpa) (result *v1alpha1.Hvpa, err error) {
	result = &v1alpha1.Hvpa{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hvpas").
		Name(hvpa.Name).
		Body(hvpa).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *hvpas) UpdateStatus(hvpa *v1alpha1.Hvpa) (result *v1alpha1.Hvpa, err error) {
	result = &v1alpha1.Hvpa{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hvpas").
		Name(hvpa.Name).
		SubResource("status").
		Body(hvpa).
		Do().
		Into(result)
	return
}

// Delete takes name of the hvpa and deletes it. Returns an error if one occurs.
func (c *hvpas) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hvpas").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hvpas) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hvpas").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched hvpa.
func (c *hvpas) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Hvpa, err error) {
	result = &v1alpha1.Hvpa{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hvpas").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
