# permissions for end users to view hvpas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hvpa-viewer-role
rules:
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - hvpas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - hvpas/status
  verbs:
  - get
