# permissions for end users to edit hvpas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hvpa-editor-role
rules:
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - hvpas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - hvpas/status
  verbs:
  - get
