#!/usr/bin/env bash
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -e

# For the test step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.

export GO111MODULE=on
export GOFLAGS=-mod=vendor

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

##############################################################################

cd ${SOURCE_PATH}

# Declare global variables
TEST_ID=

function setup_test_enviornment() {
  setup_ginkgo
  setup_env
}

function setup_ginkgo(){
    echo "Installing Ginkgo..."
    go install github.com/onsi/ginkgo/ginkgo
    echo "Successfully installed Ginkgo."
}

function setup_env(){
    echo "Downloading and installing kubebuilder..."
    go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
    echo "Successfully installed kubebuilder."
    setup-envtest use -p env 1.25.0
}

function get_test_id() {
  git_commit=`git show -s --format="%H"`
  export TEST_ID=hvpa-test-${git_commit}
  echo "Test id: ${TEST_ID}"
}

##############################################################################
function setup_test_cluster() {
  get_test_id
}

###############################################################################

setup_test_enviornment
echo "Setting up test cluster..."
setup_test_cluster

echo "Starting integration tests..."

set +e
ginkgo -r -cover utils internal controllers
TEST_RESULT=$?
set -e

echo "Done with integration tests."

echo "Successfully completed all tests."

exit $TEST_RESULT
